language: node_js
node_js:
- 5
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: info@waijule.com
  api_key:
    secure: WrXsF6+XZBMg2+oeDqx+C34W+GVONH0B6eqwoQLmGfnrUSyA8R+U95rb/QET0vzcQV0Lu65gdGFHzlA36tg81XibEFnaW3+GgURTn7Jn10T0T43l/5chqEbrY4RngQ7DfoVIpUtwfOWWPxjDW+MvC/SFwT3U6yVtPKAQz4sHdAqMHmKLU7GSavthaLAtu93RQj8mClqsS/93epbgHMn8XMRkIPMU9Xw7HdmtOBIAO/jWhHCdqC3VyjsDcChsiDnxvd0jR9GaqbJlo4AaBK8sAZ1vne/mJNP1zey5FqIugi7dOHi2A8wy3gZZeCnkGh1PGIY/bX9N0Ca6JARmFPDRqgzIKxIt8wV1e28So2CAbDqwwXwtZSVSgZkyGodad51Y98CKuvFc2bJ/rZuqwYd/Pl8qYBSm2PPUVoJE/kS87PBTpDSkFIGKxBSgqNKGjob00ddIfkXBf5hHI4JSQ9dAmfETopvuWxqXGkN7QQERfMfWTzseDEIDG8O9jxHJOBOQRX+fHIKgdqd6a56atcOZxYcSA95+xi0XXZKW5YJhVMu1w0omBxWe8XKL3jdGivFHJ//MXxHN3DqNaE+KTO2jLU8vr/pv17Q3I9UbI2aLj52K6hw15iIiTucqdFsO2Nm2c5Z3bunGXN0bcw682Bm/HK1XmKo+fShiAvzqSR8tLw8=
  on:
    tags: true
    repo: waijule/webpack-oss-plugin
